Adding logs on ojp-server for debugging.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -70,7 +70,7 @@ jobs:
         run: mvn test -pl ojp-server
 
       - name: Run (ojp-server)
-        run: mvn verify -pl ojp-server -Prun-ojp-server > ojp-server.log 2>&1 &
+        run: mvn verify -pl ojp-server -Prun-ojp-server > /tmp/ojp-server.log 2>&1 &
 
       - name: Wait for ojp-server to start
         run: sleep 10
@@ -90,7 +90,7 @@ jobs:
 
       - name: Show ojp-server.log
         if: always()  # ensures it runs even if previous steps fail
-        run: cat ojp-server.log || echo "ojp-server.log not found"
+        run: cat /tmp/ojp-server.log || echo "/tmp/ojp-server.log not found"
 
   notify-integration:
     runs-on: ubuntu-latest
